// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Note: 'seed' is invoked ONLY by 'prisma db seed' for local development & testing.
    // In production, database updates MUST use 'npx prisma migrate deploy' (which never runs seed).
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // For Prisma CLI / migration operations, use DIRECT_URL (direct port 5432, session mode)
    // if provided. Otherwise fallback to DATABASE_URL (transaction pooler or local PostgreSQL).
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
